import SwiftUI

struct SelectFilesView: View {
    @EnvironmentObject var model: InPorterModel
    
    var body: some View {
        VStack(spacing: 0) {
            // Header
            VStack(alignment: .leading, spacing: 0) {
                HStack {
                    Text("Source Media")
                        .font(.title2)
                        .bold()
                    Spacer()
                    
                    Text("\(model.activeFileItems.count) of \(model.fileItems.count) included")
                        .foregroundColor(.secondary)
                        .font(.caption)
                    
                    Button("Add More…") {
                        model.selectFilesWithPanel()
                    }
                }
                .padding()
                
                GuidedInfo(message: "InPorter has scanned your files for camera-specific metadata. It looks for 6-digit dates (MMDDYY) and trailing sequence numbers used by professional equipment to automate the renaming process in the next step.")
                    .padding(.horizontal)
                    .padding(.bottom, 10)
            }
            .background(Color(NSColor.controlBackgroundColor))
            
            Divider()
            
            // Split View
            HSplitView {
                // LEFT: File List
                VStack(spacing: 0) {
                    List {
                        ForEach(model.fileItems) { item in
                            FileRow(item: item, isSelected: model.selectedFileId == item.id)
                                .onTapGesture {
                                    model.selectedFileId = item.id
                                }
                        }
                    }
                    .listStyle(.inset)
                }
                .frame(minWidth: 300, maxWidth: .infinity)
                
                // RIGHT: Preview & Metadata
                VStack {
                    if let selectedId = model.selectedFileId,
                       let selectedItem = model.fileItems.first(where: { $0.id == selectedId }) {
                        
                        VStack(spacing: 16) {
                            VideoPlayerView(url: selectedItem.url)
                                .frame(height: 350)
                                .background(Color.black)
                                .cornerRadius(8)
                                .shadow(radius: 2)
                            
                            ScrollView {
                                VStack(alignment: .leading, spacing: 8) {
                                    Text(selectedItem.name)
                                        .font(.title3)
                                        .bold()
                                        .textSelection(.enabled)
                                    
                                    Divider()
                                    MetadataDisplayView(item: selectedItem)
                                }
                                .padding(.horizontal, 4)
                            }
                        }
                        .padding()
                        
                    } else {
                        VStack(spacing: 12) {
                            Image(systemName: "play.slash.fill")
                                .font(.system(size: 40))
                                .foregroundColor(.secondary)
                            Text("No Clip Selected")
                                .foregroundColor(.secondary)
                        }
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                    }
                }
                .frame(minWidth: 350, maxWidth: .infinity)
                .background(Color(NSColor.windowBackgroundColor))
            }
            
            Divider()
            
            // Footer
            HStack {
                if model.hasLRFFiles {
                    Toggle("Choose to not copy LRF files as well", isOn: $model.skipLRFFiles)
                        .toggleStyle(.checkbox)
                        .help("Proxy files (.LRF) are often generated by cameras like Sony. Uncheck this to save space if you don't need them.")
                }
                
                Spacer()
                
                Button("Proceed") {
                    model.proceedFromFileSelection()
                }
                .buttonStyle(.borderedProminent)
                .disabled(model.activeFileItems.isEmpty)
                .controlSize(.large)
            }
            .padding()
        }
    }
}
